# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: build and test

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.d'
      - '**.dasm'
  pull_request:
    paths:
      - '**.d'
      - '**.dasm'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dlang-community/setup-dlang@4c99aa991ce7d19dd3064de0a4f2f6b2f152e2d7

    - name: 'Build'
      run: rdmd build.d

    - name: 'Run Tests'
      run: rdmd dirttest.d 'rdmd dirtasm' tests

